### ISSUE TITLE
obi requires computer access information to be specified in project.yml

### ISSUE THREAD

**Issue by Gobiner** [Oblong/obi#97] opened 2017-02-03 03:40 UTC
It would be nice and possibly even useful if obi could use locations defined in some other place, like in our  `machine-witch` system.

**Comment by EchoAbstract** [comment] 2017-02-03 13:32
This is related (the same?) as issue #29.

**Comment by tomjakubowski** [comment] 2017-02-03 15:00
I like having all the hosts/IPs spelled out in the project.yaml, but it's a pain in the butt adding a new room. A command to add a new room based on some existing set of cmd line args/env vars and IPs defined in an Ansible inventory would be nice.

**Comment by sandover** [comment] 2017-02-03 17:26
In this design, there are pros and cons. Here are some of the pros of having a design based around a single, simple, unified project.yaml:

- easy to document
- easy to explain
- easy to share -- to make my obi work just like your obi, you give me *one thing*
- proven success in the field with users -- this model works for people
- minimizes the tool's surface area -- easier to maintain when there's no logic, machinery, conventions, or other tools needed to manage 2 things

The cons (the file could get long, adding a new room requires reconsidering all the args) are worrying at scale, but they simply have not cropped up at our scale. Until there is much more pain, or a new con emergees, or a functional difficulty or defect is discovered, I recommend no action on this or #29 and in fact I'd move to close them.

**Comment by tomjakubowski** [comment] 2017-04-11 21:59
@sandover the pains do materialize at scale. project.yaml editing time is proportional to the number of target systems (always growing) times the number of projects (growing even faster).

Nearly any time I have to do a one-off project to reproduce some bug I deal with this annoyance one way or another. Fortunately we stick warehouse room config in a couple internal obi templates, but non-warehouse users (numbers of which are also growing!) don't benefit from that, and external templates (like g-speak or greenhouse templates) don't have the warehouse config.

**Comment by tomjakubowski** [comment] 2017-04-11 22:00
I agree that having the room config explicitly spelled out in project.yaml is nice. I'm asking for a better way to add rooms to project.yaml than "copy paste and edit and then when it doesn't run, realize you forgot to change one thing, and oh oops you forgot to change another thing, rinse, repeat".

**Comment by jshrake** [comment] 2017-04-21 16:45
Duplicate of #29

**Closed by jshrake** 2017-04-21 16:45 UTC
Labels: enhancement, question
