### ISSUE TITLE
Compile fails when dir name has space

### ISSUE THREAD

**Issue by yedendra** [Oblong/obi#18] opened 2015-11-02 18:35 UTC
CMake Error: The current CMakeCache.txt directory /Users/yshrini/Working/GSpeak_training/templates/foo/build/CMakeCache.txt is different than the directory /Users/yshrini/Working/GSpeak training/templates/foo/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/Users/yshrini/Working/GSpeak_training/templates/foo/CMakeLists.txt" does not match the source "/Users/yshrini/Working/GSpeak training/templates/foo/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

Fatal error: local() encountered an error (return code 1) while executing '(cd build; cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ..)'

Aborting.

Fatal error: One or more hosts failed while executing task 'build_task'

Aborting.

**Comment by tomjakubowski** [comment] 2015-11-09 01:23
I get a different error, from a fresh `obi new greenhouse`:

```
tjakubowski@tjakubowskimbp:~/tmp/ha ha ha/wat
% obi build
[localhost] Executing task '<lambda>'
[localhost] Executing task 'build_task'
[localhost] local: mkdir -p build
[localhost] local: cmake -H/Users/tjakubowski/tmp/ha ha ha/wat -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
CMake Error: The source directory "/Users/tjakubowski/tmp/ha ha ha/wat/ha/wat" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

Fatal error: local() encountered an error (return code 1) while executing 'cmake -H/Users/tjakubowski/tmp/ha ha ha/wat -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug'

Aborting.

Fatal error: One or more hosts failed while executing task 'build_task'

Aborting.
```

I think the problem, in any case, is that these arguments aren't quoted/escaped properly (from `task.py`, line 148).

```
        # Ensure the directory exists
        env.run("mkdir -p {0}".format(env.build_dir))
        env.run("cmake -H{0} -B{1} {2}".format(env.project_dir, env.build_dir, cmake_args))
        env.run("cmake --build {0} -- {1}".format(env.build_dir, build_args))
```

**Comment by jshrake** [comment] 2016-04-14 17:10
I cannot reproduce this issue on HEAD of master, closing.

```
$ mkdir "dir with spaces"
$ cd dir\ with\ spaces
$ obi new gspeak wow
$ cd wow
$ obi go
```

**Closed by jshrake** 2016-04-14 17:10 UTC
Labels: bug
