### ISSUE TITLE
must first ssh manually into machine to use it as obi target

### ISSUE THREAD

**Issue by sandover** [Oblong/obi#107] opened 2017-04-04 15:27 UTC
. . . and type “yes” to the prompt about whether to add ssh key.

The issue isn't mentioned in the README.

**Comment by EchoAbstract** [comment] 2017-04-04 16:26
@sandover the normal use case is that you add the host to your `~/.ssh/known_hosts` file when you log in to transfer your ssh key (via `copy-ssh-id`).  We see this since `machine-wizard` deploys our keys for us instead of doing it our selves.

I do think we should have a bit in the README about dealing with SSH issues such as this or the "dreaded" `Host key verification failed` errors.

**Comment by tomjakubowski** [comment] 2017-04-04 17:33
Can obi detect an ssh "prompt" and bail out?

**Comment by jshrake** [comment] 2017-04-21 16:47
Duplicate of #42

**Closed by jshrake** 2017-04-21 16:47 UTC
