### ISSUE TITLE
obi requires gspeak to be installed to create a new project

### ISSUE THREAD

**Issue by Gobiner** [Oblong/obi#106] opened 2017-03-27 03:43 UTC
```
[~/oblong]> obi new cpp test
Traceback (most recent call last):
  File "/usr/local/Cellar/obi/HEAD-1193e12/libexec/bin/obi", line 9, in <module>
    load_entry_point('oblong-obi==3.2.1', 'console_scripts', 'obi')()
  File "/usr/local/Cellar/obi/HEAD-1193e12/libexec/lib/python2.7/site-packages/obi/obi.py", line 166, in main
    g_speak_home = get_g_speak_home(arguments)
  File "/usr/local/Cellar/obi/HEAD-1193e12/libexec/lib/python2.7/site-packages/obi/obi.py", line 106, in get_g_speak_home
    g_speak_home = max(items, key=g_speak_version_key)
ValueError: max() arg is an empty sequence
┌[aaron@candelabra] [/dev/ttys000] [candelabra ⚡] [1]
└[~/oblong]> echo $G_SPEAK_HOME

┌[aaron@candelabra] [/dev/ttys000] [candelabra ⚡]
└[~/oblong]> G_SPEAK_HOME=/tmp obi new cpp test
Found /tmp by environment variable G_SPEAK_HOME
Traceback (most recent call last):
  File "/usr/local/Cellar/obi/HEAD-1193e12/libexec/bin/obi", line 9, in <module>
    load_entry_point('oblong-obi==3.2.1', 'console_scripts', 'obi')()
  File "/usr/local/Cellar/obi/HEAD-1193e12/libexec/lib/python2.7/site-packages/obi/obi.py", line 170, in main
    g_speak_version = re.search(r'(\d+\.\d+)', g_speak_home).group()
AttributeError: 'NoneType' object has no attribute 'group'
┌[aaron@candelabra] [/dev/ttys000] [candelabra ⚡] [1]
└[~/oblong]> mkdir -p /tmp/oblong/g-speak3.28
┌[aaron@candelabra] [/dev/ttys000] [candelabra ⚡]
└[~/oblong]> export G_SPEAK_HOME=/tmp/oblong/g-speak3.28
┌[aaron@candelabra] [/dev/ttys000] [candelabra ⚡]
└[~/oblong]> obi new cpp test
Found /tmp/oblong/g-speak3.28 by environment variable G_SPEAK_HOME
Project test created successfully!
```

**Comment by tomjakubowski** [comment] 2017-03-27 23:33
this is a dupe of #61

**Closed** 2017-03-28 01:01 UTC
Labels: bug
